import {DropdownGroup} from "@common/components";

export type Preset = keyof typeof PRESET_GRIDS;

export const DROPDOWN_PRESETS: DropdownGroup<keyof typeof PRESET_GRIDS>[] = [
    {
        groupLabel: "Spaceships",
        items: [
            {id: "glider", label: "Glider"},
            {id: "lwss-vertical", label: "Lightweight Spaceship (Vertical)"},
            {id: "lwss-horizontal", label: "Lightweight Spaceship (Horizontal)"},
        ],
    },
    {
        groupLabel: "Patterns",
        items: [
            {id: "flower-explosion", label: "Flower Explosion"},
            {id: "pulsing-cross", label: "Pulsing Cross"},
            {id: "bun", label: "Bun"},
            {id: "butterfly", label: "Butterfly"},
        ],
    },
    {
        groupLabel: "Glider Guns",
        items: [{id: "gosper-glider-gun", label: "Gosper Glider Gun"}],
    },
];

export const PRESET_GRIDS = {
    glider: [
        [2, 1],
        [3, 2],
        [1, 3],
        [2, 3],
        [3, 3],
    ],
    "lwss-vertical": [
        [1, 1],
        [4, 1],
        [5, 2],
        [1, 3],
        [5, 3],
        [2, 4],
        [3, 4],
        [4, 4],
        [5, 4],
    ],
    "lwss-horizontal": [
        [2, 3],
        [2, 4],
        [2, 5],
        [2, 6],
        [3, 2],
        [3, 6],
        [4, 6],
        [5, 2],
        [5, 5],
    ],
    "flower-explosion": [
        [4, 6],
        [5, 4],
        [5, 8],
        [6, 3],
        [6, 5],
        [6, 7],
        [6, 9],
        [7, 4],
        [7, 8],
        [8, 6],
    ],
    "pulsing-cross": [
        [4, 6],
        [4, 7],
        [4, 8],
        [5, 5],
        [5, 7],
        [5, 9],
        [6, 4],
        [6, 7],
        [6, 10],
        [7, 4],
        [7, 5],
        [7, 6],
        [7, 8],
        [7, 9],
        [7, 10],
        [8, 4],
        [8, 7],
        [8, 10],
        [9, 5],
        [9, 7],
        [9, 9],
        [10, 6],
        [10, 7],
        [10, 8],
    ],
    "gosper-glider-gun": [
        [0, 24],
        [1, 22],
        [1, 24],
        [2, 12],
        [2, 13],
        [2, 20],
        [2, 21],
        [2, 34],
        [2, 35],
        [3, 11],
        [3, 15],
        [3, 20],
        [3, 21],
        [3, 34],
        [3, 35],
        [4, 0],
        [4, 1],
        [4, 10],
        [4, 16],
        [4, 20],
        [4, 21],
        [5, 0],
        [5, 1],
        [5, 10],
        [5, 14],
        [5, 16],
        [5, 17],
        [5, 22],
        [5, 24],
        [6, 10],
        [6, 16],
        [6, 24],
        [7, 11],
        [7, 15],
        [8, 12],
        [8, 13],
    ],
    bun: [
        [5, 6],
        [5, 7],
        [6, 5],
        [6, 8],
        [7, 6],
        [7, 7],
        [7, 8],
    ],
    butterfly: [
        [6, 4],
        [6, 5],
        [6, 6],
        [7, 3],
        [7, 6],
        [8, 3],
        [8, 6],
        [9, 4],
        [9, 5],
    ],
};
